export const FETCHING_VEHICLES_REQUEST = 'FETCHING_VEHICLES_REQUEST';
export const FETCHING_VEHICLES_SUCCESS = 'FETCHING_VEHICLES_SUCCESS';
export const FETCHING_VEHICLES_FAILURE = 'FETCHING_VEHICLES_FAILURE';
export const FETCHING_MORE_VEHICLES_REQUEST = 'FETCHING_MORE_VEHICLES_REQUEST';
export const FETCHING_MORE_VEHICLES_SUCCESS = 'FETCHING_MORE_VEHICLES_SUCCESS';